# 配置文件：config.yaml

email:
  sender_email: ""          # 发件人邮箱
  sender_password: ""    # 发件人邮箱密码
  recipient_email: "" # 收件人邮箱
  smtp_server: "smtp.163.com"                # 邮件服务器
  smtp_port: 465                            # 邮件端口，163邮箱默认

monitoring:
  keywords:                                 # 检测的库列表
    - "torch"
    - "tensorflow"
    - "paddlepaddle"
  check_interval: 3                        # 检测间隔（秒）